Repository scratchfoundation/scratch-blocks, pull requests merged in 2018-06, with the labels that each got.

#1555 Pass stack glow filter to the toolbox
  core/toolbox.js
  core/workspace_svg.js
Labels: pr - good to merge

#1502 Fixed lack of category identifiers
  blocks_vertical/sound.js
Labels: pr - good to merge

#1553 Don't check for the selected block in setParent
  core/block_svg.js
Labels: pr - good to merge

#1552 Clear selected block before executing undo/redo
  core/workspace.js
Labels: pr - needs review

#1568 Update the chromedriver version
  tests/scripts/get_chromedriver.sh
Labels: pr - good to merge

#1557 Comment Events
  core/block_svg.js
  core/bubble_dragger.js
  core/comment_events.js
  core/contextmenu.js
  core/events.js
  core/scratch_block_comment.js
  core/scratch_bubble.js
  core/workspace_comment.js
  core/workspace_comment_render_svg.js
  core/workspace_comment_svg.js
  core/xml.js
Labels: pr - good to merge

#1559 Add when touching hat
  blocks_vertical/event.js
  msg/messages.js
Labels: pr - good to merge

#1512 Fix the check to compile local or remote in do_compile
  build.py
Labels: pr - needs review

#1576 Fix XML Serialization for Block Comments
  core/xml.js
Labels: pr - needs review

#1573 Add missing require
  core/workspace_audio.js
Labels: pr - good to merge

#1572 Add workspace comment tests and other event tests
  tests/jsunit/event_test.js
  tests/jsunit/test_utilities.js
  tests/jsunit/vertical_tests.html
  tests/jsunit/workspace_comment_test.js
Labels: pr - good to merge

#1575 Workspace Comment Rendering & Minimize
  core/comment_events.js
  core/contextmenu.js
  core/css.js
  core/scratch_bubble.js
  core/workspace_comment.js
  core/workspace_comment_render_svg.js
  core/workspace_comment_svg.js
  tests/jsunit/workspace_comment_test.js
Labels: pr - needs review

#1578 Switch languages without reloading
  .gitignore
  cleanup.sh
  core/blockly.js
  core/flyout_base.js
  core/scratch_msgs.js
  i18n/create_scratch_msgs.js
  i18n/js_to_json.js
  i18n/json_to_js.js
  msg/js/en.js
  msg/json/en.json
  msg/messages.js
  msg/scratch_msgs.js
  package.json
  tests/vertical_playground.html
  tests/vertical_playground_compressed.html
Labels: localization, pr - good to merge

#1587 Workspace scroll bugfix and unit tests!
  core/scratch_block_comment.js
  core/xml.js
  tests/jsunit/scratch_block_comment_test.js
  tests/jsunit/vertical_tests.html
Labels: pr - good to merge

#1589 Remove explicit z-index from comment foreign body.
  core/css.js
  core/scratch_block_comment.js
  core/workspace_comment_render_svg.js
Labels: pr - needs review

#1586 Add extension status button stub
  blocks_vertical/default_toolbox.js
  core/blockly.js
  core/flyout_base.js
Labels: pr - good to merge

#1591 Fix issues with scrolling workspace just after resizing a comment.
  core/scratch_bubble.js
  core/workspace_comment_render_svg.js
Labels: pr - good to merge

#1593 Add a character limit to the comment textareas.
  core/scratch_block_comment.js
  core/workspace_comment.js
  core/workspace_comment_render_svg.js
Labels: pr - needs review

#1604 Smaller comment label length
  core/scratch_block_comment.js
  core/workspace_comment.js
Labels: pr - needs review

#1596 Update ScratchMsgs export
  core/scratch_msgs.js
  msg/scratch_msgs.js
  shim/blocks_compressed_horizontal-blockly_compressed_horizontal-messages.js
  shim/blocks_compressed_vertical-blockly_compressed_vertical-messages.js
  shim/horizontal.js
  shim/vertical.js
Labels: localization, pr - needs review

#1607 Deploy with messages
  i18n/create_scratch_msgs.js
  msg/scratch_msgs.js
  package.json
Labels: localization, pr - good to merge

#1609 Missing menu strings
  core/scratch_msgs.js
  msg/js/en.js
  msg/json/en.json
  msg/messages.js
  msg/scratch_msgs.js
Labels: localization, pr - good to merge

#1611 Localize the `stop` block
  blocks_vertical/control.js
Labels: localization, pr - good to merge

#1610 Add flyout extension category header
  blocks_vertical/default_toolbox.js
  core/blockly.js
  core/constants.js
  core/flyout_base.js
  core/flyout_button.js
  core/flyout_extension_category_header.js
  core/toolbox.js
  media/status-not-ready.svg
  media/status-ready.svg
Labels: pr - good to merge
