Repository scratchfoundation/scratch-blocks, pull requests merged in 2018-05, with the labels that each got.

#1485 Add a file for scratch-blocks-specific util functions
  core/block_render_svg_vertical.js
  core/block_svg.js
  core/field_textinput.js
  core/gesture.js
  core/scratch_blocks_utils.js
  core/utils.js
  core/workspace_svg.js
Labels: pr - good to merge

#1486 More lint and small changes from Blockly
  core/block.js
  core/block_dragger.js
  core/block_svg.js
  core/blockly.js
  core/bubble.js
  core/comment.js
  core/extensions.js
  core/field.js
  core/field_colour.js
  core/field_date.js
  core/field_dropdown.js
  core/field_image.js
  core/field_variable.js
  core/flyout_base.js
  core/flyout_button.js
  core/mutator.js
  core/scrollbar.js
  core/touch.js
  core/utils.js
Labels: pr - good to merge

#1488 Add micellaneous no-op obsolete blocks
  blocks_vertical/looks.js
  blocks_vertical/sensing.js
  msg/messages.js
Labels: pr - needs work

#1483 Add "all at once" block
  blocks_vertical/control.js
  msg/messages.js
Labels: pr - good to merge

#1484 Add scroll blocks
  blocks_vertical/motion.js
  msg/messages.js
Labels: pr - good to merge

#1494 Lint in block definitions
  blocks_horizontal/event.js
  blocks_horizontal/wedo.js
  blocks_vertical/control.js
  blocks_vertical/data.js
  blocks_vertical/event.js
  blocks_vertical/extensions.js
  blocks_vertical/looks.js
  blocks_vertical/motion.js
  blocks_vertical/operators.js
  blocks_vertical/procedures.js
  blocks_vertical/sensing.js
  blocks_vertical/sound.js
  blocks_vertical/vertical_extensions.js
Labels: pr - good to merge

#1493 More lint
  core/block.js
  core/block_drag_surface.js
  core/block_render_svg_horizontal.js
  core/block_render_svg_vertical.js
  core/block_svg.js
  core/blockly.js
  core/connection.js
  core/data_category.js
  core/dragged_connection_manager.js
  core/dropdowndiv.js
  core/field.js
  core/field_angle.js
  core/field_colour_slider.js
  core/field_dropdown.js
  core/field_iconmenu.js
  core/field_image.js
  core/field_label.js
  core/field_number.js
  core/field_numberdropdown.js
  core/field_textdropdown.js
  core/field_textinput.js
  core/field_variable.js
  core/field_vertical_separator.js
  core/flyout_horizontal.js
  core/flyout_vertical.js
  core/gesture.js
  core/inject.js
  core/input.js
  core/scratch_blocks_utils.js
  core/toolbox.js
  core/utils.js
  core/variable_map.js
  core/widgetdiv.js
  core/workspace_svg.js
  core/xml.js
Labels: pr - good to merge

#1491 New script to pull from Blockly and do basic cleanup
  cleanup.sh
  pull_from_blockly.sh
Labels: pr - good to merge

#1426 Move "new message" to top of broadcast dropdowns
  core/field_variable.js
Labels: pr - good to merge

#1496 Add new indent rule to .eslintrc and increase the minimum version
  .eslintrc
  package.json
Labels: pr - good to merge

#1425 Add "item # of (thing) in (list)" block
  blocks_vertical/data.js
  core/data_category.js
Labels: pr - needs review

#1464 Recycle blocks in Flyouts
  core/block_svg.js
  core/flyout_base.js
  core/workspace.js
Labels: pr - good to merge

#1503 chore(webpack): update to webpack 4
  .travis.yml
  package.json
  shim/blockly_compressed_horizontal-blocks_compressed.js
  shim/blockly_compressed_horizontal.js
  shim/blockly_compressed_vertical-blocks_compressed.js
  shim/blockly_compressed_vertical.js
  shim/blocks_compressed_horizontal.js
  shim/blocks_compressed_vertical.js
  shim/gh-pages.js
  shim/horizontal.js
  shim/vertical.js
  webpack.config.js
Labels: pr - good to merge

#1511 Show the show/hide blocks in the data category now that they are done.
  core/data_category.js
Labels: pr - needs review

#1514 Split events.js into multiple files
  core/block.js
  core/block_dragger.js
  core/block_events.js
  core/block_svg.js
  core/comment.js
  core/connection.js
  core/contextmenu.js
  core/events.js
  core/events_abstract.js
  core/field.js
  core/flyout_base.js
  core/gesture.js
  core/insertion_marker_manager.js
  core/mutator.js
  core/procedures.js
  core/scratch_events.js
  core/toolbox.js
  core/ui_events.js
  core/variable_events.js
  core/variable_map.js
  core/variable_model.js
  core/warning.js
  core/workspace_svg.js
  core/xml.js
  tests/jsunit/event_test.js
Labels: pr - good to merge

#1522 Add various missing translation strings
  blocks_vertical/control.js
  blocks_vertical/data.js
  blocks_vertical/event.js
  msg/js/en.js
  msg/json/en.json
  msg/messages.js
Labels: pr - good to merge

#1517 Scroll to category by id
  blocks_vertical/default_toolbox.js
  core/flyout_base.js
  core/toolbox.js
Labels: pr - good to merge

#1505 update ctm logic to fit with upstream change
  core/constants.js
  core/workspace_svg.js
Labels: pr - good to merge

#1519 Feature/merge workspace comments
  core/block.js
  core/block_dragger.js
  core/block_svg.js
  core/blockly.js
  core/bubble.js
  core/bubble_dragger.js
  core/contextmenu.js
  core/css.js
  core/gesture.js
  core/toolbox.js
  core/workspace.js
  core/workspace_comment.js
  core/workspace_comment_render_svg.js
  core/workspace_comment_svg.js
  core/workspace_svg.js
  core/ws_comment_events.js
  core/xml.js
  msg/messages.js
  tests/jsunit/horizontal_tests.html
  tests/jsunit/vertical_tests.html
  tests/jsunit/workspace_comment_test.js
  tests/vertical_playground.html
Labels: pr - good to merge

#1524 Add padding to the bottom of the flyout
  core/flyout_vertical.js
Labels: pr - good to merge

#1520 Don't allow cut or paste in the flyout
  core/blockly.js
Labels: pr - good to merge

#1539 Add the require for WorkspaceCommentSvg.render
  core/workspace_svg.js
Labels: pr - needs review

#1537 Publish only dist, TRADEMARK, README.md, package.json, and LICENSE to npm
  .npmignore
Labels: ergonomics, pr - good to merge

#1533 Add ordered option to getDescendants and all uses.
  core/block.js
  core/block_dragger.js
  core/block_svg.js
  core/contextmenu.js
  core/events.js
  core/flyout_horizontal.js
  core/flyout_vertical.js
  core/generator.js
  core/mutator.js
  core/procedures.js
  core/rendered_connection.js
  core/scratch_blocks_utils.js
  core/variables.js
  core/workspace.js
  core/workspace_svg.js
  core/xml.js
Labels: pr - needs review

#1543 Fix unclickable flyout buttons
  core/css.js
Labels: pr - needs review

#1544 Scratch Block Comments
  core/block.js
  core/block_render_svg_vertical.js
  core/block_svg.js
  core/contextmenu.js
  core/css.js
  core/flyout_base.js
  core/flyout_vertical.js
  core/scratch_block_comment.js
  core/scratch_bubble.js
  core/xml.js
  media/comment-arrow-down.svg
  media/comment-arrow-up.svg
  media/delete-x.svg
  msg/messages.js
  tests/vertical_playground_compressed.html
Labels: pr - needs review

#1508 Use shim/vertical as browser entry point
  package.json
Labels: pr - good to merge
