Repository scratchfoundation/scratch-blocks, pull requests merged in 2018-12, with the labels that each got.

#1799 Update scratch-l10n
  i18n/sync_tx_src.js
  msg/scratch_msgs.js
  package.json
Labels: localization

#1801 Fix importing cloud vars from xml.
  core/xml.js
Labels: pr - good to merge

#1806 Update and switch to reviewed translations
  i18n/sync_tx_translations.js
  msg/scratch_msgs.js
  package.json
Labels: pr - good to merge

#1810 fix reporters having extra space below text.
  core/css.js
Labels: pr - needs review

#1815 Fix extra events being emitted from the color slider
  core/field_colour_slider.js
Labels: pr - good to merge

#1812 Clear dropdown width to fix half-width bug
  core/dropdowndiv.js
Labels: pr - needs review

#1816 Conditionally turn off slider handle callbacks.
  core/field_colour_slider.js
Labels: pr - needs review

#1818 Change the order of the arrow keys
  blocks_vertical/event.js
  blocks_vertical/sensing.js
Labels: pr - good to merge

#1817 Skip variable's own name in the context menu for its reporter
  blocks_vertical/data.js
Labels: pr - good to merge

#1811 Use fill-opacity for notepicker shadow
  core/field_note.js
Labels: pr - good to merge

#1807 Use variable name as default value for rename prompts
  core/variables.js
Labels: pr - good to merge

#1838 pull new translations from transifex
  msg/scratch_msgs.js
Labels: localization
