Repository scratchfoundation/scratch-blocks, pull requests merged in 2018-04, with the labels that each got.

#1430 Add "while" block
  blocks_vertical/control.js
Labels: pr - good to merge

#1431 Add counter blocks
  blocks_vertical/control.js
Labels: pr - good to merge

#1438 use .textContent setter
  core/field.js
Labels: pr - good to merge

#1449 Move block animation code to a new file
  core/block_animations.js
  core/block_dragger.js
  core/block_svg.js
  core/dragged_connection_manager.js
  core/gesture.js
  core/insertion_marker_manager.js
Labels: pr - needs review

#1453 Local build script
  .gitignore
  local_build.sh
  package.json
Labels: pr - good to merge

#1451 Minor text adjustment to 'go to [front]' block
  blocks_vertical/looks.js
Labels: pr - good to merge

#1439 Fix some problems with shadows in custom procedure calls
  blocks_vertical/procedures.js
  core/procedures.js
  tests/custom_procedure_playground.html
Labels: pr - needs review

#1442 Recycle flyout blocks
  core/data_category.js
  core/flyout_base.js
Labels: pr - needs review

#1452 Switch to Blockly.Field.fromJson
  core/block.js
  core/field.js
  core/field_angle.js
  core/field_checkbox.js
  core/field_colour.js
  core/field_colour_slider.js
  core/field_date.js
  core/field_dropdown.js
  core/field_iconmenu.js
  core/field_image.js
  core/field_label.js
  core/field_label_serializable.js
  core/field_number.js
  core/field_numberdropdown.js
  core/field_textdropdown.js
  core/field_textinput.js
  core/field_textinput_removable.js
  core/field_variable.js
  core/field_variable_getter.js
  core/field_vertical_separator.js
  tests/jsunit/field_angle_test.js
  tests/jsunit/field_number_test.js
  tests/jsunit/field_test.js
Labels: pr - needs review

#1468 Fix vertical alignment of Flyout buttons in Firefox and Edge
  core/flyout_button.js
Labels: pr - good to merge

#1476 Revert "mouse-pointer" changes in messages
  msg/js/en.js
  msg/json/en.json
  msg/messages.js
Labels: pr - needs review

#1475 Apply small fixes in block_drag_surface.js
  .eslintrc
  core/block_drag_surface.js
Labels: pr - needs work

#1481 Store and get category length
  core/flyout_base.js
  core/toolbox.js
Labels: pr - good to merge

#1465 Don't leak input outline paths
  core/input.js
Labels: pr - good to merge

#1480 Add a function to center to workspace on a block
  core/workspace_svg.js
Labels: pr - good to merge

#1477 Decompose functions in core/zoom_controls.js
  core/zoom_controls.js
Labels: pr - good to merge

#1474 Add referencesVariables function to fields
  core/block.js
  core/field.js
  core/field_variable.js
  core/field_variable_getter.js
  core/xml.js
Labels: pr - good to merge

#1479 Lint that caused conflicts with Blockly; mark things protected
  .eslintrc
  core/block.js
  core/block_svg.js
  core/blockly.js
  core/blocks.js
  core/bubble.js
  core/comment.js
  core/connection.js
  core/connection_db.js
  core/contextmenu.js
  core/extensions.js
  core/flyout_base.js
  core/flyout_button.js
  core/grid.js
  core/icon.js
  core/mutator.js
  core/names.js
  core/rendered_connection.js
  core/scrollbar.js
  core/tooltip.js
  core/trashcan.js
  core/ui_menu_utils.js
  core/utils.js
  core/variable_map.js
  core/variable_model.js
  core/warning.js
  core/widgetdiv.js
  core/workspace.js
  core/workspace_audio.js
  core/workspace_drag_surface_svg.js
  core/workspace_dragger.js
  core/workspace_svg.js
  core/xml.js
Labels: pr - good to merge
