Repository scratchfoundation/scratch-blocks, pull requests merged in 2018-11, with the labels that each got.

#1769 Disable pointer events on field angle arrow to fix firefox dragging
  core/css.js
  core/field_angle.js
Labels: pr - good to merge

#1770 Ensmallen the delete area to not extend above and below the flyout
  core/flyout_vertical.js
Labels: pr - needs review

#1767 Gave the drag handle a bit more spacing to avoid glow getting cut
  core/field_angle.js
Labels: pr - good to merge

#1763 Musical note picker field
  blocks_common/note.js
  blocks_vertical/default_toolbox.js
  blocks_vertical/extensions.js
  core/blockly.js
  core/css.js
  core/field_note.js
  media/icons/arrow_button.svg
  tests/vertical_playground.html
Labels: pr - good to merge

#1774 Sync translations with Transifex
  msg/scratch_msgs.js
Labels: localization

#1772 Fix local compile on Windows
  build.py
Labels: pr - needs review, windows

#1781 Make insertion markers for define blocks have the correct width
  core/block_render_svg_vertical.js
Labels: pr - good to merge

#1780 Support scientific notation in numerical inputs
  core/field_number.js
Labels: pr - needs work

#1782 Track cloud variable info
  core/variable_events.js
  core/variable_map.js
  core/variable_model.js
  core/variables.js
  core/workspace.js
  core/workspace_svg.js
  core/xml.js
  tests/jsunit/event_test.js
Labels: pr - good to merge

#1785 sync translations with Transifex
  msg/scratch_msgs.js
Labels: localization

#1786 Add "random direction" to "point towards" dropdown
  blocks_vertical/motion.js
  msg/js/en.js
  msg/json/en.json
  msg/messages.js
  msg/scratch_msgs.js
Labels: pr - good to merge

#1787 Update scratch-l10n to the latest version
  msg/scratch_msgs.js
  package.json
Labels: pr - good to merge

#1791 Sync translations with transifex
  msg/scratch_msgs.js
Labels: localization
