Repository scratchfoundation/scratch-blocks, pull requests merged in 2018-03, with the labels that each got.

#1393 Use the parent SVG to get the blocks area.
  core/workspace_svg.js
Labels: pr - good to merge

#1382 Fix behavior of color picker on sensor blocks
  core/css.js
  core/field_colour_slider.js
Labels: pr - needs work

#1400 Prevent jumping up a category when switching sprites
  core/flyout_base.js
Labels: pr - needs review

#1404 Don’t scroll the toolbox to the top on populate
  core/toolbox.js
Labels: pr - needs review

#1398 Remove 'help' option from block context menu
  core/block_svg.js
Labels: pr - good to merge

#1407 Support for scroll position stability
  core/flyout_base.js
  core/toolbox.js
Labels: pr - needs review

#1371 Make sensing "key pressed" block input droppable
  blocks_vertical/default_toolbox.js
  blocks_vertical/sensing.js
Labels: pr - needs review

#1413 Improve visibility of stack glow
  core/colours.js
  core/constants.js
  core/inject.js
  core/workspace_svg.js
Labels: pr - needs review

#1412 Add event_whenstageclicked block definition
  blocks_vertical/event.js
Labels: pr - needs review

#1394 Add for-each block
  blocks_vertical/control.js
Labels: pr - good to merge

#1421 Shrink scrollbar size on touch devices.
  core/scrollbar.js
Labels: pr - good to merge
