Repository scratchfoundation/scratch-blocks, pull requests merged in 2018-10, with the labels that each got.

#1727 Sync translations from Transifex
  msg/scratch_msgs.js
Labels: localization

#1726 Bugfixes for RTL Comments
  core/block_events.js
  core/bubble.js
  core/comment_events.js
  core/scratch_block_comment.js
  core/scratch_bubble.js
  core/workspace.js
  core/workspace_comment_render_svg.js
  core/workspace_comment_svg.js
  core/xml.js
  tests/jsunit/event_test.js
Labels: pr - good to merge

#1728 Remove default code generators & clarify connection to Scratch VM
  .eslintignore
  .gitignore
  README.md
  build.py
  build/gen_generator.js
  cleanup.sh
  dart_compressed.js
  generators/dart.js
  generators/javascript.js
  generators/lua.js
  generators/php.js
  generators/python.js
  javascript_compressed.js
  lua_compressed.js
  package.json
  php_compressed.js
  python_compressed.js
Labels: pr - needs review

#1732 Sync translations with transifex
  msg/scratch_msgs.js
Labels: localization

#1731 Menu items can be functions, to support the 'record...' option
  blocks_vertical/sound.js
  core/field_dropdown.js
  msg/messages.js
Labels: pr - good to merge

#1739 Fixes webpack problem breaking 'npm install'
  package.json
Labels: pr - needs review

#1738 fixed missing argType declaration
  core/field_variable.js
Labels: pr - good to merge

#1741 Fix number picker positioning above block
  core/field_number.js
Labels: pr - good to merge

#1742 When duplicating on touch, don't start a drag with the new blocks
  core/block_svg.js
  core/contextmenu.js
  core/scratch_blocks_utils.js
Labels: pr - good to merge

#1740 Darken droppable menu inputs when menu is open.
  core/block.js
  core/block_render_svg_vertical.js
  core/field_dropdown.js
Labels: pr - good to merge

#1744 Use grandparent block colours for number picker dropdowns
  core/field_number.js
Labels: pr - good to merge

#1743 Fix #1345. Android triggers a window resize event when the soft keyb…
  core/blockly.js
  core/inject.js
  core/widgetdiv.js
Labels: pr - needs review

#1746 Choose sensible defaults for custom procedure parameters.
  blocks_vertical/procedures.js
Labels: pr - good to merge

#1747 Initialize currentDragDeltaXY_ correctly
  core/gesture.js
Labels: pr - needs review

#1748 Remove unneeded logs
  core/gesture.js
  core/workspace_svg.js
Labels: pr - needs review

#1750 Use different text for variable and list deletion/renaming
  core/field_variable.js
  msg/messages.js
Labels: pr - needs review

#1751 Don't allow illegal connections to procedure prototype blocks
  core/connection.js
  tests/custom_procedure_playground.html
Labels: pr - needs review

#1753 Update translations
  msg/js/en.js
  msg/json/en.json
  msg/scratch_msgs.js
Labels: localization

#1687 Utility function cleanup for merges
  core/block_svg.js
  core/bubble.js
  core/bubble_dragger.js
  core/comment.js
  core/inject.js
  core/scrollbar.js
  core/touch.js
  core/trashcan.js
  core/utils.js
  core/workspace_drag_surface_svg.js
Labels: pr - good to merge

#1754 Add some missing utility functions
  core/utils.js
Labels: pr - good to merge

#1755 Fix procedure definition blocks with trailing text
  core/block_render_svg_vertical.js
Labels: pr - needs review

#1752 Automate translation update
  i18n/sync_tx_src.js
  i18n/sync_tx_translations.js
  i18n/test_scratch_msgs.js
  msg/scratch_msgs.js
  package.json
Labels: ergonomics, localization, pr - good to merge

#1756 Remove custom touch handling for dropdowns
  core/field_dropdown.js
Labels: pr - needs review

#1757 Allow block comments to be editable on mobile by catching the mousedo…
  core/comment.js
  core/scratch_block_comment.js
Labels: pr - needs review

#1761 Update translations
  msg/scratch_msgs.js
Labels: localization
