Repository scratchfoundation/scratch-blocks, pull requests merged in 2018-07, with the labels that each got.

#1622 Add menu option for loudness in "when > _" hat block
  blocks_vertical/event.js
  msg/messages.js
Labels: pr - good to merge

#1621 Local Variables
  core/variable_events.js
  core/variable_map.js
  core/variable_model.js
  core/variables.js
  core/workspace.js
  core/workspace_svg.js
  core/xml.js
  tests/jsunit/event_test.js
Labels: pr - good to merge

#1634 Regenerate en.json to include new key
  msg/js/en.js
  msg/json/en.json
  msg/scratch_msgs.js
Labels: localization, pr - good to merge

#1560 Add new menu type field matrix
  blocks_common/matrix.js
  blocks_vertical/default_toolbox.js
  blocks_vertical/extensions.js
  core/blockly.js
  core/css.js
  core/field_matrix.js
  media/extensions/microbit-block-icon.svg
  tests/vertical_playground.html
Labels: pr - good to merge

#1637 Change the extension button status so it can be kept up-to-date.
  core/blockly.js
  core/flyout_base.js
  core/flyout_extension_category_header.js
Labels: pr - needs review

#1639 Use the new status ready and status not ready icons
  core/flyout_extension_category_header.js
  media/status-not-ready.svg
  media/status-ready.svg
Labels: pr - needs review

#1640 Add "delete all of [list]" block
  blocks_vertical/data.js
  core/data_category.js
  msg/js/en.js
  msg/json/en.json
  msg/messages.js
  msg/scratch_msgs.js
Labels: pr - good to merge

#1641 Separate updating translations from generating src.
  core/scratch_msgs.js
  package.json
Labels: pr - good to merge

#1642 Pull latest translations from transifex
  msg/scratch_msgs.js
Labels: localization

#1643 Update translations
  msg/scratch_msgs.js
Labels: localization

#1644 Rename Variable Bugfix
  core/variables.js
Labels: pr - needs review

#1646 Issue/widen category
  core/css.js
  core/toolbox.js
Labels: localization, pr - good to merge

#1649 Update motion.js
  blocks_vertical/motion.js
Labels: pr - good to merge

#1648 Issue/1618 split nextbackdrop
  blocks_vertical/looks.js
  msg/js/en.js
  msg/json/en.json
  msg/messages.js
  msg/scratch_msgs.js
Labels: localization, pr - good to merge

#1651 Log warning instead of throwing error on variable conflicts
  core/variable_map.js
Labels: pr - good to merge

#1652 Issue/2546 missing thing
  core/data_category.js
  msg/js/en.js
  msg/json/en.json
  msg/messages.js
  msg/scratch_msgs.js
Labels: localization, pr - good to merge

#1655 Update translations prior to conference
  msg/scratch_msgs.js
Labels: localization

#1656 Check for additional placeholders in translations
  i18n/create_scratch_msgs.js
  msg/scratch_msgs.js
Labels: localization, pr - good to merge

#1427 Fix scroll speed on Firefox
  core/constants.js
  core/workspace_svg.js
Labels: pr - needs review

#1661 When opt_noId is specified to true, shadow ids should also be removed.
  core/xml.js
Labels: pr - good to merge

#1536 Add ability to overwrite default block colours
  .gitignore
  core/options.js
Labels: pr - good to merge

#1659 Add block separators to list category
  core/data_category.js
Labels: pr - good to merge
