Repository scratchfoundation/scratch-blocks, pull requests merged in 2018-08, with the labels that each got.

#1667 Make extension status button clickable on Windows Edge
  core/css.js
Labels: pr - good to merge

#1668 RTL positioning for category labels and buttons in the flyout.
  core/flyout_extension_category_header.js
  core/flyout_vertical.js
Labels: pr - needs review

#1665 Don't break on a null mutation
  core/insertion_marker_manager.js
Labels: pr - good to merge

#1674 Only take keypresses when visible
  core/blockly.js
  core/workspace_svg.js
Labels: pr - needs review

#1678 Sync transtions with Transifex
  .tx/config
  msg/scratch_msgs.js
Labels: localization

#1670 Make holding shift to scroll work on Firefox
  core/workspace_svg.js
Labels: pr - needs review

#1664 Throw Errors instead of using goog.asserts
  core/block.js
  core/block_drag_surface.js
  core/block_dragger.js
  core/block_events.js
  core/block_svg.js
  core/bubble_dragger.js
  core/connection.js
  core/connection_db.js
  core/contextmenu.js
  core/events.js
  core/extensions.js
  core/field.js
  core/field_dropdown.js
  core/field_textinput.js
  core/field_variable.js
  core/flyout_base.js
  core/flyout_dragger.js
  core/flyout_horizontal.js
  core/flyout_vertical.js
  core/generator.js
  core/gesture.js
  core/input.js
  core/rendered_connection.js
  core/scrollbar.js
  core/tooltip.js
  core/utils.js
  core/workspace.js
  core/workspace_comment_svg.js
  core/workspace_drag_surface_svg.js
  core/workspace_dragger.js
  core/workspace_svg.js
  core/xml.js
Labels: pr - good to merge

#1693 Move code for pasing colour options into colours.js
  core/colours.js
  core/options.js
Labels: pr - good to merge

#1688 Move to utils
  core/block_svg.js
  core/contextmenu.js
  core/flyout_base.js
  core/scratch_blocks_utils.js
Labels: pr - good to merge

#1677 Place newly-created custom blocks in the top left of the visible workspace
  core/procedures.js
Labels: pr - good to merge

#1676 Avoid dragging comment's line
  core/scratch_bubble.js
Labels: pr - good to merge

#1698 Revert "Throw Errors instead of using goog.asserts"
  core/block.js
  core/block_drag_surface.js
  core/block_dragger.js
  core/block_events.js
  core/block_svg.js
  core/bubble_dragger.js
  core/connection.js
  core/connection_db.js
  core/contextmenu.js
  core/events.js
  core/extensions.js
  core/field.js
  core/field_dropdown.js
  core/field_textinput.js
  core/field_variable.js
  core/flyout_base.js
  core/flyout_dragger.js
  core/flyout_horizontal.js
  core/flyout_vertical.js
  core/generator.js
  core/gesture.js
  core/input.js
  core/rendered_connection.js
  core/scrollbar.js
  core/tooltip.js
  core/utils.js
  core/workspace.js
  core/workspace_comment_svg.js
  core/workspace_drag_surface_svg.js
  core/workspace_dragger.js
  core/workspace_svg.js
  core/xml.js
Labels: critical, pr - good to merge

#1702 Handle RTL text
  core/css.js
  core/dropdowndiv.js
  core/field.js
Labels: localization, pr - good to merge
