Repository scratchfoundation/scratch-blocks, pull requests merged in 2019-01, with the labels that each got.

#1821 Scroll very long context menus
  core/css.js
  core/widgetdiv.js
Labels: pr - needs review

#1841 "Say something" for block comment
  core/contextmenu.js
Labels: pr - good to merge

#1868 Pull new translations from transifex
  msg/scratch_msgs.js
Labels: localization

#1870 Add new languages.
  msg/scratch_msgs.js
  package.json
Labels: localization

#1876 update translations from transifex
  msg/scratch_msgs.js
Labels: localization

#1790 Add class to category menu item based on id
  core/toolbox.js
Labels: pr - good to merge

#1881 Manually calculate the bounding box of the flyout since we have all t…
  core/flyout_vertical.js
Labels: performance, pr - good to merge

#1882 pull updated translations from Transifex
  msg/scratch_msgs.js
Labels: localization, pr - good to merge
