Repository scratchfoundation/scratch-blocks, pull requests merged in 2019-03, with the labels that each got.

#1902 Remove 'To JavaScript' button
  tests/vertical_playground.html
Labels: pr - needs review

#1911 Update translations from transifex
  msg/scratch_msgs.js
Labels: localization

#1914 Update argument reporter names in the define stack after mutation change
  blocks_vertical/procedures.js
Labels: pr - good to merge

#1828 Add restrictor to disallow text being typed in "direction" block input
  core/field_angle.js
Labels: pr - good to merge

#1896 Fix build
  blocks_vertical/procedures.js
  build.py
Labels: pr - good to merge

#1921 Update translations from Transifex
  msg/scratch_msgs.js
Labels: localization
