Repository scratchfoundation/scratch-blocks, pull requests merged in 2019-02, with the labels that each got.

#1887 Speed up the connection DB
  core/connection_db.js
  tests/jsunit/connection_db_test.js
Labels: pr - needs review

#1891 Pull updated translations from Transifex
  msg/scratch_msgs.js
Labels: localization

#1888 Sort context menu variable list
  blocks_vertical/data.js
Labels: pr - good to merge

#1892 added persian and central kurdish
  msg/scratch_msgs.js
  package.json
Labels: needs qa, pr - good to merge

#1894 Fix flyout button
  core/flyout_button.js
Labels: pr - needs review
