Repository scratchfoundation/scratch-blocks, pull requests merged in 2019-07, with the labels that each got.

#1942 Handle promise rejection for sound.play() in preload
  core/workspace_audio.js
Labels: critical, pr - needs review

#1960 Fix numpad to work correctly with moving cursors
  core/field_number.js
Labels: pr - good to merge

#1961 Allow quiet inputs to be focused by typing
  core/field_textinput.js
Labels: pr - needs work

#1965 Add Khmer and sync translations
  msg/scratch_msgs.js
  package.json
Labels: pr - good to merge

#1966 add Georgian
  msg/scratch_msgs.js
  package.json
Labels: localization, pr - good to merge

#1967 Move call to focus element outside of the the setTimeout. iOS is pick…
  core/workspace_comment_render_svg.js
Labels: pr - good to merge

#1970 Several fixes for comments
  core/scratch_block_comment.js
  core/scratch_bubble.js
  core/workspace_comment_render_svg.js
Labels: pr - good to merge

#1971 Use placeholders instead of default text for comments, fix focusing
  core/contextmenu.js
  core/css.js
  core/scratch_block_comment.js
  core/workspace_comment_render_svg.js
Labels: pr - good to merge

#1975 More touchable comments, and a few RTL bugfixes
  core/scratch_bubble.js
  core/workspace_comment_render_svg.js
  media/comment-arrow-down.svg
  media/comment-arrow-up.svg
  media/delete-x.svg
Labels: pr - good to merge
