Repository scratchfoundation/scratch-blocks, pull requests merged in 2020-06, with the labels that each got.

#2066 Use FieldColourSlider's internal hue_, saturation_, brightness_ in slider callbacks
  core/field_colour_slider.js
Labels: pr - good to merge

#2079 Update l10n dependency and pull Mongolian
  msg/scratch_msgs.js
  package-lock.json
  package.json
Labels: localization, pr - good to merge

#2077 on Windows, use google-closure-compiler.cmd
  build.py
Labels: developer facing, pr - good to merge, windows
