Repository scratchfoundation/scratch-blocks, pull requests merged in 2020-05, with the labels that each got.

#2065 Bump Travis Node version to 12
  .travis.yml
Labels: pr - good to merge

#2067 Add Armenian (hy)
  msg/scratch_msgs.js
  package.json
Labels: localization, pr - good to merge

#2070 Update translations
  msg/scratch_msgs.js
  package-lock.json
  package.json
Labels: localization
